_wandb:
    value:
        cli_version: 0.19.11
        code_path: source-predict_house_price-c__Users_ASUS_Desktop_Mlop_prj_fecth_data.ipynb
        m: []
        python_version: 3.12.7
        session_history: code\_session_history.ipynb
        t:
            "1":
                - 55
            "2":
                - 55
            "3":
                - 2
                - 23
                - 55
            "4": 3.12.7
            "5": 0.19.11
            "8":
                - 1
                - 3
                - 5
            "12": 0.19.11
            "13": windows-amd64
